### PR TITLE
Update the HE role name in dependency section

### PR DESCRIPTION
**Pull request by tiraboschi**
Update HE role name according to
https://galaxy.ansible.com/ovirt/hosted_engine_setup

See: https://github.com/ansible/galaxy/issues/1128

### CODE REVIEW

**Comment by tiraboschi** [comment]
@machacekondra @mwperina can you please review?

**Review by eslutsky — APPROVED** [review]
Looks good

**Review by machacekondra — APPROVED** [review]
Note that you can still ask Ansible team rename the name, if you want to use dashes instead. But they must do it, it's not possible via UI.

**Review by kobihk — APPROVED** [review]

**Comment by kobihk** [comment]
@machacekondra without this PR I got:
- downloading role 'hosted-engine-setup', owned by oVirt
 [WARNING]: - oVirt.hosted-engine-setup was NOT installed successfully: - sorry, oVirt.hosted-engine-setup was not found on https://galaxy.ansible.com.

ERROR! - you can use --ignore-errors to skip failed roles and finish processing the list.

**Comment by machacekondra** [comment]
Yes, right now the name is "oVirt.hosted_engine_setup"

**Pull request merged**
