### PR TITLE
The role doesn't work fine due to qcow_url variable name

### PR DESCRIPTION
**Pull request by rsevilla87**
The variable name qcow_url should be modified to qcow2_url since qcow2_url is evaluated in the role main.yml.

### CODE REVIEW

**Comment by ovirt-infra** [comment]
The commiter is not a member of organization nor whitelist. Please contact maintainer for patch verification.

**Comment by ovirt-infra** [comment]
The commiter is not a member of organization nor whitelist. Please contact maintainer for patch verification.

**Comment by ovirt-infra** [comment]
The commiter is not a member of organization nor whitelist. Please contact maintainer for patch verification.

**Comment by ovirt-infra** [comment]
The commiter is not a member of organization nor whitelist. Please contact maintainer for patch verification.

**Comment by ovirt-infra** [comment]
The commiter is not a member of organization nor whitelist. Please contact maintainer for patch verification.

**Comment by ovirt-infra** [comment]
The commiter is not a member of organization nor whitelist. Please contact maintainer for patch verification.

**Comment by ovirt-infra** [comment]
The commiter is not a member of organization nor whitelist. Please contact maintainer for patch verification.

**Comment by ovirt-infra** [comment]
The commiter is not a member of organization nor whitelist. Please contact maintainer for patch verification.

**Comment by ovirt-infra** [comment]
The commiter is not a member of organization nor whitelist. Please contact maintainer for patch verification.

**Comment by ovirt-infra** [comment]
The commiter is not a member of organization nor whitelist. Please contact maintainer for patch verification.

**Comment by ovirt-infra** [comment]
The commiter is not a member of organization nor whitelist. Please contact maintainer for patch verification.

**Comment by ovirt-infra** [comment]
The commiter is not a member of organization nor whitelist. Please contact maintainer for patch verification.

**Comment by ovirt-infra** [comment]
The commiter is not a member of organization nor whitelist. Please contact maintainer for patch verification.

**Comment by ovirt-infra** [comment]
The commiter is not a member of organization nor whitelist. Please contact maintainer for patch verification.

**Comment by ovirt-infra** [comment]
The commiter is not a member of organization nor whitelist. Please contact maintainer for patch verification.

**Comment by ovirt-infra** [comment]
The commiter is not a member of organization nor whitelist. Please contact maintainer for patch verification.

**Comment by eedri** [comment]
ci test please

**Comment by tremble** [comment]
qcow_url was the documented variable and the previously valid variable, what's the rationale behind changing it just because glance support was added?

Surely to avoid breaking other people's playbooks it qcow2_url should be replaced with qcow_url.

**Comment by machacekondra** [comment]
Thank you for fixing the issue. We shouldn't change a variable name, as we keep our variables backward compatible. There is an issue in a check of properly passed variables here[1].

So it would be better to change the `main.yml` to something like:

```yaml
---
- name: Fail when invalid parameters
  fail:
    msg: "You must either specify qcow_url or glance_image variable"
  when: "glance_image is defined and qcow_url is defined"

- name: Glance image
  include: glance_image.yml
  when: "glance_image is defined"

- name: QCOW2 image
  include: qcow2_image.yml
when: "qcow_url is defined"
```

[1] https://github.com/oVirt/ovirt-ansible/blob/master/roles/ovirt-image-template/tasks/main.yml#L4

**Comment by tremble** [comment]
@machacekondra As I'd done in #55 ?

I closed it since this PR exists, but to get the correct fix would it be worth reopening that one and closing this?

**Comment by machacekondra** [comment]
@tremble Right, I've missed your PR, I will merge yours and close this one. Thanks a lot.

**Pull request closed without merging**
