### PR TITLE
Add vdsm-conf role

### PR DESCRIPTION
**Pull request by machacekondra**
Role to change VDSM configuration on hosts.

```yaml
---
- name: VDSM configuration
  hosts: localhost
  connection: local
  gather_facts: false

  vars_files:
    # Contains encrypted `engine_password` varibale using ansible-vault
    - passwords.yml

  vars:
    engine_url: https://ondra.local:8443/ovirt-engine/api
    engine_user: admin@internal

    host_names:
      - host1
    vdsm_file_path: /etc/vdsm/logger.conf
    vdsm_configuration:
      - section: logger_root
        option: level
        value: DEBUG
      - section: logger_vds
        option: level
        value: DEBUG

  roles:
    - vdsm-conf
```

Execution example:
```bash
 $ ansible-playbook --private-key=~/ovirt-engine/etc/pki/ovirt-engine/keys/engine_id_rsa examples/vdsm_conf.ymll


PLAY [VDSM configuration] *****************************************************************************************************************************************************************************************

TASK [vdsm-conf : Fail if user didn't specify proper input parameters] ********************************************************************************************************************************************
skipping: [127.0.0.1]

TASK [vdsm-conf : Login to oVirt] *********************************************************************************************************************************************************************************
ok: [127.0.0.1]

TASK [vdsm-conf : Fetch hosts in cluster] *************************************************************************************************************************************************************************
skipping: [127.0.0.1]

TASK [vdsm-conf : Print info about host which will be modified] ***************************************************************************************************************************************************
skipping: [127.0.0.1]

TASK [vdsm-conf : Run the modification of the VDSM for the host] **************************************************************************************************************************************************
skipping: [127.0.0.1]

TASK [vdsm-conf : Run the modification of the VDSM for the host] **************************************************************************************************************************************************
included: /home/omachace/workspace/ovirt-ansible/roles/vdsm-conf/tasks/modify_vdsm.yml for 127.0.0.1

TASK [vdsm-conf : Fetch power management settings] ****************************************************************************************************************************************************************
ok: [127.0.0.1]

TASK [vdsm-conf : Fail if host wasn't found] **********************************************************************************************************************************************************************
skipping: [127.0.0.1]

TASK [vdsm-conf : Check if only one host for the name was found] **************************************************************************************************************************************************
skipping: [127.0.0.1]

TASK [vdsm-conf : Remember power management settings] *************************************************************************************************************************************************************
ok: [127.0.0.1]

TASK [vdsm-conf : Check if VDSM configuration change is indeed needed with dry mode] ******************************************************************************************************************************
changed: [127.0.0.1 -> 10.34.60.25] => (item={u'section': u'logger_root', u'option': u'level', u'value': u'DEBUG'})
changed: [127.0.0.1 -> 10.34.60.25] => (item={u'section': u'logger_vds', u'option': u'level', u'value': u'DEBUG'})

TASK [vdsm-conf : Disable power management] ***********************************************************************************************************************************************************************
changed: [127.0.0.1]

TASK [vdsm-conf : Stop VDSM] **************************************************************************************************************************************************************************************
changed: [127.0.0.1 -> 10.34.60.25]

TASK [vdsm-conf : Change the VDSM configraution] ******************************************************************************************************************************************************************
changed: [127.0.0.1 -> 10.34.60.25] => (item={u'section': u'logger_root', u'option': u'level', u'value': u'DEBUG'})
changed: [127.0.0.1 -> 10.34.60.25] => (item={u'section': u'logger_vds', u'option': u'level', u'value': u'DEBUG'})

TASK [vdsm-conf : Start VDSM] *************************************************************************************************************************************************************************************
changed: [127.0.0.1 -> 10.34.60.25]

TASK [vdsm-conf : Wait till the host is UP in engine] *************************************************************************************************************************************************************
FAILED - RETRYING: Wait till the host is UP in engine (6 retries left).
ok: [127.0.0.1]

TASK [vdsm-conf : Restore power management settings] **************************************************************************************************************************************************************
changed: [127.0.0.1]

TASK [vdsm-conf : Logout from oVirt] ******************************************************************************************************************************************************************************
ok: [127.0.0.1]

PLAY RECAP ********************************************************************************************************************************************************************************************************
127.0.0.1                  : ok=12   changed=6    unreachable=0    failed=0   
```

### CODE REVIEW

**Comment by machacekondra** [comment]
@mwperina @oourfali @mykaul @mgoldboi

**Comment by mykaul** [comment]
Isn't there a standard way in Ansible to change conf files?

**Comment by machacekondra** [comment]
> Isn't there a standard way in Ansible to change conf files?

Not sure, what do you mean. There is a module `ini_file`, which modifies the configuration file.

**Comment by mykaul** [comment]
I remember seeing something like:
ansible -i hosts.ini vdsm -u root  -m ini_file --args="dest=/etc/vdsm/vdsm.
conf.d/50-profile.conf section=devel option=cpu_profile_enable value=true"

**Comment by machacekondra** [comment]
Yes, this executes the `ini_file` module. We execute it as well, here: https://github.com/oVirt/ovirt-ansible/pull/41/files#diff-0bd7d7f6037ef737ab2c3249119148b6R59
```yaml
  - name: Change the VDSM configraution
    ini_file:
      path: "{{ vdsm_file_path }}"
      section: "{{ vdsm_var.section | default('vars') }}"
      option: "{{ vdsm_var.option | mandatory }}"
      value: "{{ vdsm_var.value | mandatory }}"
      backup: "{{ configuration_backup }}"
    delegate_to: "{{ ovirt_hosts[0].address }}"
    with_items:
      - "{{ vdsm_configuration | mandatory }}"
    loop_control:
      loop_var: vdsm_var
```

**Review by rhodain — CHANGES_REQUESTED** [review]
Shouldn't we enable the configuration backup by default?

**Comment by mwperina** [comment]
Few comments from my side:

1. Host needs to be in Maintenance, otherwise we cannot alter configuration and restart vdsm service
2. I don't like the idea of updating directly /etc/vdsm/vdsm.conf, it seems better to me to create for example /etc/vdsm/vdsm.conf.d/10-ovirt-vdsm.conf file which will be created/updated only by this role
3. Unfortunately logging cannot be configured using vdsm.conf.d, so this would be a special case

Overall I think it's an oVirt 4.3 RFE.

**Comment by mwperina** [comment]
Development moved to https://github.com/ovirt/ovirt-ansible-collection If this is still relevant, please reopen there.

**Pull request closed without merging**
