### PR TITLE
ovirt-image-template: Replace references to qcow2_url added by glance support

### PR DESCRIPTION
**Pull request by tremble**
The documentation references qcow_url *not* qcow2_url, as do the original tasks.

### CODE REVIEW

**Comment by ovirt-infra** [comment]
Hello contributor, thanks for submitting a PR for an oVirt project! 

I am the bot who triggers CI builds on the oVirt Jenkins server. 
In order to allow this PR to run fully automated tests, you can do one of the following options:

1. Asking one of the project maintainers to add you to the project team ( it's done via GitHub admin page for the project )
2. If you are planning to contribute to more than one project, maybe it's better to ask them to add you to the oVirt organization, so you'll be able to run tests for all oVirt's projects.
3. Asking one of the maintainers to run the 'ci test please' on the PR.


Note: You might see multiple messages like this showing up on a single PR, this is due to a known bug in the GitHub trigger plugin on Jenkins, the oVirt infra team is working on fixing this via new testing flow in the near future, so we'll be able to post a single message per PR.

**Comment by ovirt-infra** [comment]
Hello contributor, thanks for submitting a PR for an oVirt project! 

I am the bot who triggers CI builds on the oVirt Jenkins server. 
In order to allow this PR to run fully automated tests, you can do one of the following options:

1. Asking one of the project maintainers to add you to the project team ( it's done via GitHub admin page for the project )
2. If you are planning to contribute to more than one project, maybe it's better to ask them to add you to the oVirt organization, so you'll be able to run tests for all oVirt's projects.
3. Asking one of the maintainers to run the 'ci test please' on the PR.


Note: You might see multiple messages like this showing up on a single PR, this is due to a known bug in the GitHub trigger plugin on Jenkins, the oVirt infra team is working on fixing this via new testing flow in the near future, so we'll be able to post a single message per PR.

**Comment by ovirt-infra** [comment]
Hello contributor, thanks for submitting a PR for an oVirt project! 

I am the bot who triggers CI builds on the oVirt Jenkins server. 
In order to allow this PR to run fully automated tests, you can do one of the following options:

1. Asking one of the project maintainers to add you to the project team ( it's done via GitHub admin page for the project )
2. If you are planning to contribute to more than one project, maybe it's better to ask them to add you to the oVirt organization, so you'll be able to run tests for all oVirt's projects.
3. Asking one of the maintainers to run the 'ci test please' on the PR.


Note: You might see multiple messages like this showing up on a single PR, this is due to a known bug in the GitHub trigger plugin on Jenkins, the oVirt infra team is working on fixing this via new testing flow in the near future, so we'll be able to post a single message per PR.

**Comment by ovirt-infra** [comment]
Hello contributor, thanks for submitting a PR for an oVirt project! 

I am the bot who triggers CI builds on the oVirt Jenkins server. 
In order to allow this PR to run fully automated tests, you can do one of the following options:

1. Asking one of the project maintainers to add you to the project team ( it's done via GitHub admin page for the project )
2. If you are planning to contribute to more than one project, maybe it's better to ask them to add you to the oVirt organization, so you'll be able to run tests for all oVirt's projects.
3. Asking one of the maintainers to run the 'ci test please' on the PR.


Note: You might see multiple messages like this showing up on a single PR, this is due to a known bug in the GitHub trigger plugin on Jenkins, the oVirt infra team is working on fixing this via new testing flow in the near future, so we'll be able to post a single message per PR.

**Comment by ovirt-infra** [comment]
Hello contributor, thanks for submitting a PR for an oVirt project! 

I am the bot who triggers CI builds on the oVirt Jenkins server. 
In order to allow this PR to run fully automated tests, you can do one of the following options:

1. Asking one of the project maintainers to add you to the project team ( it's done via GitHub admin page for the project )
2. If you are planning to contribute to more than one project, maybe it's better to ask them to add you to the oVirt organization, so you'll be able to run tests for all oVirt's projects.
3. Asking one of the maintainers to run the 'ci test please' on the PR.


Note: You might see multiple messages like this showing up on a single PR, this is due to a known bug in the GitHub trigger plugin on Jenkins, the oVirt infra team is working on fixing this via new testing flow in the near future, so we'll be able to post a single message per PR.

**Comment by ovirt-infra** [comment]
Hello contributor, thanks for submitting a PR for an oVirt project! 

I am the bot who triggers CI builds on the oVirt Jenkins server. 
In order to allow this PR to run fully automated tests, you can do one of the following options:

1. Asking one of the project maintainers to add you to the project team ( it's done via GitHub admin page for the project )
2. If you are planning to contribute to more than one project, maybe it's better to ask them to add you to the oVirt organization, so you'll be able to run tests for all oVirt's projects.
3. Asking one of the maintainers to run the 'ci test please' on the PR.


Note: You might see multiple messages like this showing up on a single PR, this is due to a known bug in the GitHub trigger plugin on Jenkins, the oVirt infra team is working on fixing this via new testing flow in the near future, so we'll be able to post a single message per PR.

**Comment by ovirt-infra** [comment]
Hello contributor, thanks for submitting a PR for an oVirt project! 

I am the bot who triggers CI builds on the oVirt Jenkins server. 
In order to allow this PR to run fully automated tests, you can do one of the following options:

1. Asking one of the project maintainers to add you to the project team ( it's done via GitHub admin page for the project )
2. If you are planning to contribute to more than one project, maybe it's better to ask them to add you to the oVirt organization, so you'll be able to run tests for all oVirt's projects.
3. Asking one of the maintainers to run the 'ci test please' on the PR.


Note: You might see multiple messages like this showing up on a single PR, this is due to a known bug in the GitHub trigger plugin on Jenkins, the oVirt infra team is working on fixing this via new testing flow in the near future, so we'll be able to post a single message per PR.

**Comment by ovirt-infra** [comment]
Hello contributor, thanks for submitting a PR for an oVirt project! 

I am the bot who triggers CI builds on the oVirt Jenkins server. 
In order to allow this PR to run fully automated tests, you can do one of the following options:

1. Asking one of the project maintainers to add you to the project team ( it's done via GitHub admin page for the project )
2. If you are planning to contribute to more than one project, maybe it's better to ask them to add you to the oVirt organization, so you'll be able to run tests for all oVirt's projects.
3. Asking one of the maintainers to run the 'ci test please' on the PR.


Note: You might see multiple messages like this showing up on a single PR, this is due to a known bug in the GitHub trigger plugin on Jenkins, the oVirt infra team is working on fixing this via new testing flow in the near future, so we'll be able to post a single message per PR.

**Comment by ovirt-infra** [comment]
Hello contributor, thanks for submitting a PR for an oVirt project! 

I am the bot who triggers CI builds on the oVirt Jenkins server. 
In order to allow this PR to run fully automated tests, you can do one of the following options:

1. Asking one of the project maintainers to add you to the project team ( it's done via GitHub admin page for the project )
2. If you are planning to contribute to more than one project, maybe it's better to ask them to add you to the oVirt organization, so you'll be able to run tests for all oVirt's projects.
3. Asking one of the maintainers to run the 'ci test please' on the PR.


Note: You might see multiple messages like this showing up on a single PR, this is due to a known bug in the GitHub trigger plugin on Jenkins, the oVirt infra team is working on fixing this via new testing flow in the near future, so we'll be able to post a single message per PR.

**Comment by ovirt-infra** [comment]
Hello contributor, thanks for submitting a PR for an oVirt project! 

I am the bot who triggers CI builds on the oVirt Jenkins server. 
In order to allow this PR to run fully automated tests, you can do one of the following options:

1. Asking one of the project maintainers to add you to the project team ( it's done via GitHub admin page for the project )
2. If you are planning to contribute to more than one project, maybe it's better to ask them to add you to the oVirt organization, so you'll be able to run tests for all oVirt's projects.
3. Asking one of the maintainers to run the 'ci test please' on the PR.


Note: You might see multiple messages like this showing up on a single PR, this is due to a known bug in the GitHub trigger plugin on Jenkins, the oVirt infra team is working on fixing this via new testing flow in the near future, so we'll be able to post a single message per PR.

**Comment by ovirt-infra** [comment]
Hello contributor, thanks for submitting a PR for an oVirt project! 

I am the bot who triggers CI builds on the oVirt Jenkins server. 
In order to allow this PR to run fully automated tests, you can do one of the following options:

1. Asking one of the project maintainers to add you to the project team ( it's done via GitHub admin page for the project )
2. If you are planning to contribute to more than one project, maybe it's better to ask them to add you to the oVirt organization, so you'll be able to run tests for all oVirt's projects.
3. Asking one of the maintainers to run the 'ci test please' on the PR.


Note: You might see multiple messages like this showing up on a single PR, this is due to a known bug in the GitHub trigger plugin on Jenkins, the oVirt infra team is working on fixing this via new testing flow in the near future, so we'll be able to post a single message per PR.

**Comment by ovirt-infra** [comment]
Hello contributor, thanks for submitting a PR for an oVirt project! 

I am the bot who triggers CI builds on the oVirt Jenkins server. 
In order to allow this PR to run fully automated tests, you can do one of the following options:

1. Asking one of the project maintainers to add you to the project team ( it's done via GitHub admin page for the project )
2. If you are planning to contribute to more than one project, maybe it's better to ask them to add you to the oVirt organization, so you'll be able to run tests for all oVirt's projects.
3. Asking one of the maintainers to run the 'ci test please' on the PR.


Note: You might see multiple messages like this showing up on a single PR, this is due to a known bug in the GitHub trigger plugin on Jenkins, the oVirt infra team is working on fixing this via new testing flow in the near future, so we'll be able to post a single message per PR.

**Comment by ovirt-infra** [comment]
Hello contributor, thanks for submitting a PR for an oVirt project! 

I am the bot who triggers CI builds on the oVirt Jenkins server. 
In order to allow this PR to run fully automated tests, you can do one of the following options:

1. Asking one of the project maintainers to add you to the project team ( it's done via GitHub admin page for the project )
2. If you are planning to contribute to more than one project, maybe it's better to ask them to add you to the oVirt organization, so you'll be able to run tests for all oVirt's projects.
3. Asking one of the maintainers to run the 'ci test please' on the PR.


Note: You might see multiple messages like this showing up on a single PR, this is due to a known bug in the GitHub trigger plugin on Jenkins, the oVirt infra team is working on fixing this via new testing flow in the near future, so we'll be able to post a single message per PR.

**Comment by ovirt-infra** [comment]
Hello contributor, thanks for submitting a PR for an oVirt project! 

I am the bot who triggers CI builds on the oVirt Jenkins server. 
In order to allow this PR to run fully automated tests, you can do one of the following options:

1. Asking one of the project maintainers to add you to the project team ( it's done via GitHub admin page for the project )
2. If you are planning to contribute to more than one project, maybe it's better to ask them to add you to the oVirt organization, so you'll be able to run tests for all oVirt's projects.
3. Asking one of the maintainers to run the 'ci test please' on the PR.


Note: You might see multiple messages like this showing up on a single PR, this is due to a known bug in the GitHub trigger plugin on Jenkins, the oVirt infra team is working on fixing this via new testing flow in the near future, so we'll be able to post a single message per PR.

**Comment by ovirt-infra** [comment]
Hello contributor, thanks for submitting a PR for an oVirt project! 

I am the bot who triggers CI builds on the oVirt Jenkins server. 
In order to allow this PR to run fully automated tests, you can do one of the following options:

1. Asking one of the project maintainers to add you to the project team ( it's done via GitHub admin page for the project )
2. If you are planning to contribute to more than one project, maybe it's better to ask them to add you to the oVirt organization, so you'll be able to run tests for all oVirt's projects.
3. Asking one of the maintainers to run the 'ci test please' on the PR.


Note: You might see multiple messages like this showing up on a single PR, this is due to a known bug in the GitHub trigger plugin on Jenkins, the oVirt infra team is working on fixing this via new testing flow in the near future, so we'll be able to post a single message per PR.

**Comment by ovirt-infra** [comment]
Hello contributor, thanks for submitting a PR for an oVirt project! 

I am the bot who triggers CI builds on the oVirt Jenkins server. 
In order to allow this PR to run fully automated tests, you can do one of the following options:

1. Asking one of the project maintainers to add you to the project team ( it's done via GitHub admin page for the project )
2. If you are planning to contribute to more than one project, maybe it's better to ask them to add you to the oVirt organization, so you'll be able to run tests for all oVirt's projects.
3. Asking one of the maintainers to run the 'ci test please' on the PR.


Note: You might see multiple messages like this showing up on a single PR, this is due to a known bug in the GitHub trigger plugin on Jenkins, the oVirt infra team is working on fixing this via new testing flow in the near future, so we'll be able to post a single message per PR.

**Comment by tremble** [comment]
Cancelling there's another pull request in progress.

**Comment by ovirt-infra** [comment]
Hello contributor, thanks for submitting a PR for an oVirt project! 

I am the bot who triggers CI builds on the oVirt Jenkins server. 
In order to allow this PR to run fully automated tests, you can do one of the following options:

1. Asking one of the project maintainers to add you to the project team ( it's done via GitHub admin page for the project )
2. If you are planning to contribute to more than one project, maybe it's better to ask them to add you to the oVirt organization, so you'll be able to run tests for all oVirt's projects.
3. Asking one of the maintainers to run the 'ci test please' on the PR.


Note: You might see multiple messages like this showing up on a single PR, this is due to a known bug in the GitHub trigger plugin on Jenkins, the oVirt infra team is working on fixing this via new testing flow in the near future, so we'll be able to post a single message per PR.

**Comment by ovirt-infra** [comment]
Hello contributor, thanks for submitting a PR for an oVirt project! 

I am the bot who triggers CI builds on the oVirt Jenkins server. 
In order to allow this PR to run fully automated tests, you can do one of the following options:

1. Asking one of the project maintainers to add you to the project team ( it's done via GitHub admin page for the project )
2. If you are planning to contribute to more than one project, maybe it's better to ask them to add you to the oVirt organization, so you'll be able to run tests for all oVirt's projects.
3. Asking one of the maintainers to run the 'ci test please' on the PR.


Note: You might see multiple messages like this showing up on a single PR, this is due to a known bug in the GitHub trigger plugin on Jenkins, the oVirt infra team is working on fixing this via new testing flow in the near future, so we'll be able to post a single message per PR.

**Comment by ovirt-infra** [comment]
Hello contributor, thanks for submitting a PR for an oVirt project! 

I am the bot who triggers CI builds on the oVirt Jenkins server. 
In order to allow this PR to run fully automated tests, you can do one of the following options:

1. Asking one of the project maintainers to add you to the project team ( it's done via GitHub admin page for the project )
2. If you are planning to contribute to more than one project, maybe it's better to ask them to add you to the oVirt organization, so you'll be able to run tests for all oVirt's projects.
3. Asking one of the maintainers to run the 'ci test please' on the PR.


Note: You might see multiple messages like this showing up on a single PR, this is due to a known bug in the GitHub trigger plugin on Jenkins, the oVirt infra team is working on fixing this via new testing flow in the near future, so we'll be able to post a single message per PR.

**Comment by ovirt-infra** [comment]
Hello contributor, thanks for submitting a PR for an oVirt project! 

I am the bot who triggers CI builds on the oVirt Jenkins server. 
In order to allow this PR to run fully automated tests, you can do one of the following options:

1. Asking one of the project maintainers to add you to the project team ( it's done via GitHub admin page for the project )
2. If you are planning to contribute to more than one project, maybe it's better to ask them to add you to the oVirt organization, so you'll be able to run tests for all oVirt's projects.
3. Asking one of the maintainers to run the 'ci test please' on the PR.


Note: You might see multiple messages like this showing up on a single PR, this is due to a known bug in the GitHub trigger plugin on Jenkins, the oVirt infra team is working on fixing this via new testing flow in the near future, so we'll be able to post a single message per PR.

**Comment by ovirt-infra** [comment]
Hello contributor, thanks for submitting a PR for an oVirt project! 

I am the bot who triggers CI builds on the oVirt Jenkins server. 
In order to allow this PR to run fully automated tests, you can do one of the following options:

1. Asking one of the project maintainers to add you to the project team ( it's done via GitHub admin page for the project )
2. If you are planning to contribute to more than one project, maybe it's better to ask them to add you to the oVirt organization, so you'll be able to run tests for all oVirt's projects.
3. Asking one of the maintainers to run the 'ci test please' on the PR.


Note: You might see multiple messages like this showing up on a single PR, this is due to a known bug in the GitHub trigger plugin on Jenkins, the oVirt infra team is working on fixing this via new testing flow in the near future, so we'll be able to post a single message per PR.

**Comment by ovirt-infra** [comment]
Hello contributor, thanks for submitting a PR for an oVirt project! 

I am the bot who triggers CI builds on the oVirt Jenkins server. 
In order to allow this PR to run fully automated tests, you can do one of the following options:

1. Asking one of the project maintainers to add you to the project team ( it's done via GitHub admin page for the project )
2. If you are planning to contribute to more than one project, maybe it's better to ask them to add you to the oVirt organization, so you'll be able to run tests for all oVirt's projects.
3. Asking one of the maintainers to run the 'ci test please' on the PR.


Note: You might see multiple messages like this showing up on a single PR, this is due to a known bug in the GitHub trigger plugin on Jenkins, the oVirt infra team is working on fixing this via new testing flow in the near future, so we'll be able to post a single message per PR.

**Comment by ovirt-infra** [comment]
Hello contributor, thanks for submitting a PR for an oVirt project! 

I am the bot who triggers CI builds on the oVirt Jenkins server. 
In order to allow this PR to run fully automated tests, you can do one of the following options:

1. Asking one of the project maintainers to add you to the project team ( it's done via GitHub admin page for the project )
2. If you are planning to contribute to more than one project, maybe it's better to ask them to add you to the oVirt organization, so you'll be able to run tests for all oVirt's projects.
3. Asking one of the maintainers to run the 'ci test please' on the PR.


Note: You might see multiple messages like this showing up on a single PR, this is due to a known bug in the GitHub trigger plugin on Jenkins, the oVirt infra team is working on fixing this via new testing flow in the near future, so we'll be able to post a single message per PR.

**Comment by ovirt-infra** [comment]
Hello contributor, thanks for submitting a PR for an oVirt project! 

I am the bot who triggers CI builds on the oVirt Jenkins server. 
In order to allow this PR to run fully automated tests, you can do one of the following options:

1. Asking one of the project maintainers to add you to the project team ( it's done via GitHub admin page for the project )
2. If you are planning to contribute to more than one project, maybe it's better to ask them to add you to the oVirt organization, so you'll be able to run tests for all oVirt's projects.
3. Asking one of the maintainers to run the 'ci test please' on the PR.


Note: You might see multiple messages like this showing up on a single PR, this is due to a known bug in the GitHub trigger plugin on Jenkins, the oVirt infra team is working on fixing this via new testing flow in the near future, so we'll be able to post a single message per PR.

**Comment by ovirt-infra** [comment]
Hello contributor, thanks for submitting a PR for an oVirt project! 

I am the bot who triggers CI builds on the oVirt Jenkins server. 
In order to allow this PR to run fully automated tests, you can do one of the following options:

1. Asking one of the project maintainers to add you to the project team ( it's done via GitHub admin page for the project )
2. If you are planning to contribute to more than one project, maybe it's better to ask them to add you to the oVirt organization, so you'll be able to run tests for all oVirt's projects.
3. Asking one of the maintainers to run the 'ci test please' on the PR.


Note: You might see multiple messages like this showing up on a single PR, this is due to a known bug in the GitHub trigger plugin on Jenkins, the oVirt infra team is working on fixing this via new testing flow in the near future, so we'll be able to post a single message per PR.

**Comment by ovirt-infra** [comment]
Hello contributor, thanks for submitting a PR for an oVirt project! 

I am the bot who triggers CI builds on the oVirt Jenkins server. 
In order to allow this PR to run fully automated tests, you can do one of the following options:

1. Asking one of the project maintainers to add you to the project team ( it's done via GitHub admin page for the project )
2. If you are planning to contribute to more than one project, maybe it's better to ask them to add you to the oVirt organization, so you'll be able to run tests for all oVirt's projects.
3. Asking one of the maintainers to run the 'ci test please' on the PR.


Note: You might see multiple messages like this showing up on a single PR, this is due to a known bug in the GitHub trigger plugin on Jenkins, the oVirt infra team is working on fixing this via new testing flow in the near future, so we'll be able to post a single message per PR.

**Comment by ovirt-infra** [comment]
Hello contributor, thanks for submitting a PR for an oVirt project! 

I am the bot who triggers CI builds on the oVirt Jenkins server. 
In order to allow this PR to run fully automated tests, you can do one of the following options:

1. Asking one of the project maintainers to add you to the project team ( it's done via GitHub admin page for the project )
2. If you are planning to contribute to more than one project, maybe it's better to ask them to add you to the oVirt organization, so you'll be able to run tests for all oVirt's projects.
3. Asking one of the maintainers to run the 'ci test please' on the PR.


Note: You might see multiple messages like this showing up on a single PR, this is due to a known bug in the GitHub trigger plugin on Jenkins, the oVirt infra team is working on fixing this via new testing flow in the near future, so we'll be able to post a single message per PR.

**Comment by ovirt-infra** [comment]
Hello contributor, thanks for submitting a PR for an oVirt project! 

I am the bot who triggers CI builds on the oVirt Jenkins server. 
In order to allow this PR to run fully automated tests, you can do one of the following options:

1. Asking one of the project maintainers to add you to the project team ( it's done via GitHub admin page for the project )
2. If you are planning to contribute to more than one project, maybe it's better to ask them to add you to the oVirt organization, so you'll be able to run tests for all oVirt's projects.
3. Asking one of the maintainers to run the 'ci test please' on the PR.


Note: You might see multiple messages like this showing up on a single PR, this is due to a known bug in the GitHub trigger plugin on Jenkins, the oVirt infra team is working on fixing this via new testing flow in the near future, so we'll be able to post a single message per PR.

**Comment by ovirt-infra** [comment]
Hello contributor, thanks for submitting a PR for an oVirt project! 

I am the bot who triggers CI builds on the oVirt Jenkins server. 
In order to allow this PR to run fully automated tests, you can do one of the following options:

1. Asking one of the project maintainers to add you to the project team ( it's done via GitHub admin page for the project )
2. If you are planning to contribute to more than one project, maybe it's better to ask them to add you to the oVirt organization, so you'll be able to run tests for all oVirt's projects.
3. Asking one of the maintainers to run the 'ci test please' on the PR.


Note: You might see multiple messages like this showing up on a single PR, this is due to a known bug in the GitHub trigger plugin on Jenkins, the oVirt infra team is working on fixing this via new testing flow in the near future, so we'll be able to post a single message per PR.

**Comment by ovirt-infra** [comment]
Hello contributor, thanks for submitting a PR for an oVirt project! 

I am the bot who triggers CI builds on the oVirt Jenkins server. 
In order to allow this PR to run fully automated tests, you can do one of the following options:

1. Asking one of the project maintainers to add you to the project team ( it's done via GitHub admin page for the project )
2. If you are planning to contribute to more than one project, maybe it's better to ask them to add you to the oVirt organization, so you'll be able to run tests for all oVirt's projects.
3. Asking one of the maintainers to run the 'ci test please' on the PR.


Note: You might see multiple messages like this showing up on a single PR, this is due to a known bug in the GitHub trigger plugin on Jenkins, the oVirt infra team is working on fixing this via new testing flow in the near future, so we'll be able to post a single message per PR.

**Comment by ovirt-infra** [comment]
Hello contributor, thanks for submitting a PR for an oVirt project! 

I am the bot who triggers CI builds on the oVirt Jenkins server. 
In order to allow this PR to run fully automated tests, you can do one of the following options:

1. Asking one of the project maintainers to add you to the project team ( it's done via GitHub admin page for the project )
2. If you are planning to contribute to more than one project, maybe it's better to ask them to add you to the oVirt organization, so you'll be able to run tests for all oVirt's projects.
3. Asking one of the maintainers to run the 'ci test please' on the PR.


Note: You might see multiple messages like this showing up on a single PR, this is due to a known bug in the GitHub trigger plugin on Jenkins, the oVirt infra team is working on fixing this via new testing flow in the near future, so we'll be able to post a single message per PR.

**Comment by ovirt-infra** [comment]
Hello contributor, thanks for submitting a PR for an oVirt project! 

I am the bot who triggers CI builds on the oVirt Jenkins server. 
In order to allow this PR to run fully automated tests, you can do one of the following options:

1. Asking one of the project maintainers to add you to the project team ( it's done via GitHub admin page for the project )
2. If you are planning to contribute to more than one project, maybe it's better to ask them to add you to the oVirt organization, so you'll be able to run tests for all oVirt's projects.
3. Asking one of the maintainers to run the 'ci test please' on the PR.


Note: You might see multiple messages like this showing up on a single PR, this is due to a known bug in the GitHub trigger plugin on Jenkins, the oVirt infra team is working on fixing this via new testing flow in the near future, so we'll be able to post a single message per PR.

**Comment by machacekondra** [comment]
ci build please

**Review by machacekondra — APPROVED** [review]

**Pull request merged**
