### PR TITLE
Split roles

### PR DESCRIPTION
**Pull request by machacekondra**
This patch is removing all the roles. Those roles are now handled in
separate git repostiories:

 - https://github.com/ovirt/ovirt-ansible-manageiq
 - https://github.com/ovirt/ovirt-ansible-infra
 - https://github.com/ovirt/ovirt-ansible-vm-infra
 - https://github.com/ovirt/ovirt-ansible-cluster-upgrade
 - https://github.com/ovirt/ovirt-ansible-image-template

The host deploy roles are part of ovirt-engine.

### CODE REVIEW

**Comment by machacekondra** [comment]
ci buid please

**Comment by machacekondra** [comment]
ci buid please

**Comment by machacekondra** [comment]
ci build please

**Comment by machacekondra** [comment]
ci build please

**Comment by machacekondra** [comment]
ci build please

**Review by mwperina — APPROVED** [review]

**Comment by machacekondra** [comment]
ci build please

**Comment by machacekondra** [comment]
ci build please

**Pull request merged**
