### PR TITLE
Add post-tasks empty file to sysconf directory

### PR DESCRIPTION
**Pull request by machacekondra**
This PR create a directory `/etc/ovirt-ansible-roles/` with permissions 0755. In this directory it creates a file `ovirt-host-deploy-post-tasks.yml` owner by root. This file is automatically loaded right after `host-deploy` role execution ends.

### CODE REVIEW

**Comment by machacekondra** [comment]
@mwperina

**Review by mwperina — APPROVED** [review]
👍

**Comment by mwperina** [comment]
One more comment: Shouldn't /etc/ovirt-ansible-roles/ovirt-host-deploy-post-tasks.yml be owned by ovirt users with 0666 permissions?

**Comment by machacekondra** [comment]
> One more comment: Shouldn't /etc/ovirt-ansible-roles/ovirt-host-deploy-post-tasks.yml be owned by ovirt users with 0666 permissions?

Well, the ovirt user won't be changing(writing) that file. Wrinting to that file will be root user, and it can be world readable.
So I think 644 for root:root, should be fine.

**Comment by mwperina** [comment]
OK, makes sense. Let's merge it 👍

**Comment by machacekondra** [comment]
ci build please

**Comment by machacekondra** [comment]
ci please build

**Comment by mwperina** [comment]
ci build please

**Comment by ifireball** [comment]
ok, yeah I see this does not work, trying to debug

**Comment by ifireball** [comment]
ci build please

**Comment by ifireball** [comment]
oh... I see... this can't work on merged PR... it must be done **before** it is merged...

**Comment by eedri** [comment]
And there is no way to trigger it manually somehow post merge?

**Comment by ifireball** [comment]
The `ovirt-ansible_master_github_build-artifacts-*` could be triggered manually, be we would need to figure out what are the correct parameters to make them build and deploy master, and one would need to manually trigger all the jobs for all platforms and architectures.

I tried with the following parameters:
1. sha1: m
2. REFSPEC: +refs/heads/master:m

This seems to work:
http://jenkins.ovirt.org/job/ovirt-ansible_master_github_build-artifacts-el7-x86_64/29

And also get deployed to 'tested':
http://jenkins.ovirt.org/job/deploy-to_ovirt-master_tested/672/

**Pull request merged**
