### PR TITLE
Add oVirt.shutdown-env

### PR DESCRIPTION
**Pull request by tiraboschi**

### CODE REVIEW

**Review by mwperina — CHANGES_REQUESTED** [review]
Please update also meta/main.yml to define role dependency for Ansible Galaxy (and of course publish your new role into Galaxy if you haven't done that already)

**Comment by tiraboschi** [comment]
I published https://galaxy.ansible.com/tiraboschi/ovirt_ansible_shutdown_env but I don't think I've the permission to publish https://galaxy.ansible.com/ovirt/ovirt_ansible_shutdown_env

**Review by mwperina — APPROVED** [review]

**Comment by mwperina** [comment]
> I published https://galaxy.ansible.com/tiraboschi/ovirt_ansible_shutdown_env but I don't think I've the permission to publish https://galaxy.ansible.com/ovirt/ovirt_ansible_shutdown_env

Ondro, could you please take a look?

@machacekondra

**Comment by machacekondra** [comment]
@tiraboschi You are now part of oVirt org on galaxy. So you should be able to do it.

**Comment by machacekondra** [comment]
@tiraboschi Unfortunately galaxy changed policy[1] for role-names, not sure why, but now:

```
Starting in v3.0, Galaxy no longer perform this calculation. Instead, the default role name is the unaltered repository name, with a couple minor exceptions, including: converting the name to all lowercase, and replacing any ‘-‘ or ‘.’ characters with ‘_’.
```

So please rename the role to use `_`.

[1] https://galaxy.ansible.com/docs/contributing/creating_role.html#role-names

**Comment by tiraboschi** [comment]
@machacekondra was https://github.com/oVirt/ovirt-ansible-shutdown-env/commit/a6e7d12af16046e180af7be28d464e039ca30ab6 enough for that?

**Comment by machacekondra** [comment]
@tiraboschi Nono, please rename all occurances of `oVirt.shutdown-env` to `oVirt.shutdown_env`

**Pull request merged**
