### PR TITLE
Added release branch configuration

### PR DESCRIPTION
**Pull request by ifireball**
Added a mapping of the main release branches to oVirt change queues.

This makes the oVirt CI system automatically build changes pushed or
merged into those branches and push them into the specified change
queues for automated system testing and release.

The following change must be merged in oVirt Gerrit before this change
can be merged and take effect:
- https://gerrit.ovirt.org/c/82786/

### CODE REVIEW

**Review by mwperina — APPROVED** [review]

**Review by machacekondra — APPROVED** [review]

**Comment by ifireball** [comment]
You merged before I finished setting up the webhook in github... I was hoping to get an end-to-end test by merging this...

**Comment by ifireball** [comment]
Also, this probably need to also be cherry picked to the 1.0 branch.

**Comment by machacekondra** [comment]
Ah, sorry I didn't know. I thought this can be merged right after merge of the gerrit patch.
I've already cherry picked.

**Comment by ifireball** [comment]
Nevermind, GitHub eventually triggered the webhook anyway:
http://jenkins.ovirt.org/blue/organizations/jenkins/oVirt_ovirt-ansible_standard-on-ghpush/detail/oVirt_ovirt-ansible_standard-on-ghpush/1/pipeline

It also ran for 1.0:
http://jenkins.ovirt.org/blue/organizations/jenkins/oVirt_ovirt-ansible_standard-on-ghpush/detail/oVirt_ovirt-ansible_standard-on-ghpush/2/pipeline

**Comment by machacekondra** [comment]
It's in tested by it's not in ovirt-master-snapshot:

 http://resources.ovirt.org/pub/ovirt-master-snapshot/rpm/el7/noarch/

Anything else I need to do for it?

**Comment by ifireball** [comment]
The '*-spanshot' repo gets updated nightly. it will get there tonight.

**Pull request merged**
